In [4]:
#Data Cleaning

import pandas as pd

In [5]:
facebook = pd.read_csv("facebook.csv")
facebook.columns

Index(['date', 'campaign_id', 'campaign_name', 'ad_set_id', 'ad_set_name',
       'impressions', 'clicks', 'spend', 'conversions', 'video_views',
       'engagement_rate', 'reach', 'frequency'],
      dtype='object')

In [6]:
facebook = facebook.rename(columns = {"spend" : "cost"})

In [7]:
facebook = facebook[[
    "date",
    "campaign_name",
    "impressions",
    "clicks",
    "cost",
    "conversions"
]]

In [8]:
facebook["platform"] = "Facebook"
facebook.head(10)

,date,campaign_name,impressions,clicks,cost,conversions,platform
0,2024-01-01,Brand_Awareness_Q1,45623,892,127.5,12,Facebook
1,2024-01-01,Conversions_Retargeting,12456,567,215.8,34,Facebook
2,2024-01-01,Traffic_Drive_Jan,34567,1234,189.9,23,Facebook
3,2024-01-02,Brand_Awareness_Q1,42345,823,118.2,10,Facebook
4,2024-01-02,Conversions_Retargeting,13678,623,234.5,38,Facebook
5,2024-01-02,Traffic_Drive_Jan,36789,1345,201.3,25,Facebook
6,2024-01-03,Brand_Awareness_Q1,48234,967,134.8,14,Facebook
7,2024-01-03,Conversions_Retargeting,11234,489,198.7,31,Facebook
8,2024-01-03,Traffic_Drive_Jan,38901,1456,213.4,28,Facebook
9,2024-01-04,Brand_Awareness_Q1,51234,1023,142.3,15,Facebook

In [9]:
facebook.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           110 non-null    object
 1   campaign_name  110 non-null    object
 2   impressions    110 non-null    int64
 3   clicks         110 non-null    int64
 4   cost           110 non-null    float64
 5   conversions    110 non-null    int64
 6   platform       110 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 6.1+ KB

In [10]:
google = pd.read_csv("google.csv")

In [11]:
google.columns

Index(['date', 'campaign_id', 'campaign_name', 'ad_group_id', 'ad_group_name',
       'impressions', 'clicks', 'cost', 'conversions', 'conversion_value',
       'ctr', 'avg_cpc', 'quality_score', 'search_impression_share'],
      dtype='object')

In [12]:
google = google[[
    "date",
    "campaign_name",
    "impressions",
    "clicks",
    "cost",
    "conversions"
]]

In [13]:
google["platform"] = "Google"

In [14]:
google.head(10)

,date,campaign_name,impressions,clicks,cost,conversions,platform
0,2024-01-01,Search_Brand_Terms,23456,1234,234.5,45,Google
1,2024-01-01,Search_Generic_Terms,45678,890,567.8,23,Google
2,2024-01-01,Shopping_All_Products,67890,2345,423.6,67,Google
3,2024-01-02,Search_Brand_Terms,24567,1289,245.6,48,Google
4,2024-01-02,Search_Generic_Terms,43234,823,534.2,21,Google
5,2024-01-02,Shopping_All_Products,71234,2456,445.8,71,Google
6,2024-01-03,Search_Brand_Terms,22345,1123,213.4,42,Google
7,2024-01-03,Search_Generic_Terms,47890,967,623.5,25,Google
8,2024-01-03,Display_Remarketing,123456,456,123.4,12,Google
9,2024-01-04,Search_Brand_Terms,25678,1345,256.7,50,Google

In [15]:
google.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           110 non-null    object
 1   campaign_name  110 non-null    object
 2   impressions    110 non-null    int64
 3   clicks         110 non-null    int64
 4   cost           110 non-null    float64
 5   conversions    110 non-null    int64
 6   platform       110 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 6.1+ KB

In [16]:
tiktok = pd.read_csv("tiktok.csv")
tiktok.columns

Index(['date', 'campaign_id', 'campaign_name', 'adgroup_id', 'adgroup_name',
       'impressions', 'clicks', 'cost', 'conversions', 'video_views',
       'video_watch_25', 'video_watch_50', 'video_watch_75', 'video_watch_100',
       'likes', 'shares', 'comments'],
      dtype='object')

In [17]:
tiktok = tiktok[[
    "date",
    "campaign_name",
    "impressions",
    "clicks",
    "cost",
    "conversions"
]]

In [18]:
tiktok["platform"] = "TikTok"

In [19]:
tiktok.head(10)

,date,campaign_name,impressions,clicks,cost,conversions,platform
0,2024-01-01,Awareness_GenZ,234567,3456,456.7,34,TikTok
1,2024-01-01,Conversion_Focus,123456,2345,678.9,67,TikTok
2,2024-01-01,Traffic_Campaign,189234,2890,345.6,23,TikTok
3,2024-01-02,Awareness_GenZ,245678,3678,478.9,36,TikTok
4,2024-01-02,Conversion_Focus,134567,2567,712.3,71,TikTok
5,2024-01-02,Traffic_Campaign,198345,3012,361.2,25,TikTok
6,2024-01-03,Awareness_GenZ,223456,3234,434.5,32,TikTok
7,2024-01-03,Conversion_Focus,112345,2123,623.4,62,TikTok
8,2024-01-03,Influencer_Collab,345678,5678,890.1,89,TikTok
9,2024-01-04,Awareness_GenZ,256789,3890,512.3,39,TikTok

In [20]:
tiktok.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           110 non-null    object
 1   campaign_name  110 non-null    object
 2   impressions    110 non-null    int64
 3   clicks         110 non-null    int64
 4   cost           110 non-null    float64
 5   conversions    110 non-null    int64
 6   platform       110 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 6.1+ KB

In [23]:
social_ads = pd.concat([facebook, google, tiktok])

In [25]:
social_ads.head(10)

,date,campaign_name,impressions,clicks,cost,conversions,platform
0,2024-01-01,Brand_Awareness_Q1,45623,892,127.5,12,Facebook
1,2024-01-01,Conversions_Retargeting,12456,567,215.8,34,Facebook
2,2024-01-01,Traffic_Drive_Jan,34567,1234,189.9,23,Facebook
3,2024-01-02,Brand_Awareness_Q1,42345,823,118.2,10,Facebook
4,2024-01-02,Conversions_Retargeting,13678,623,234.5,38,Facebook
5,2024-01-02,Traffic_Drive_Jan,36789,1345,201.3,25,Facebook
6,2024-01-03,Brand_Awareness_Q1,48234,967,134.8,14,Facebook
7,2024-01-03,Conversions_Retargeting,11234,489,198.7,31,Facebook
8,2024-01-03,Traffic_Drive_Jan,38901,1456,213.4,28,Facebook
9,2024-01-04,Brand_Awareness_Q1,51234,1023,142.3,15,Facebook

In [26]:
social_ads.shape

(330, 7)

In [27]:
social_ads["platform"].value_counts()

platform
Facebook    110
Google      110
TikTok      110
Name: count, dtype: int64

In [31]:
#Analysis time! 
#KPIs for all platforms
total_spend = social_ads["cost"].sum()
total_conversions = social_ads["conversions"].sum()
total_clicks = social_ads["clicks"].sum()
total_impressions = social_ads["impressions"].sum()

In [29]:
conversion_rate = total_conversions / total_clicks
cpa = total_spend / total_conversions
ctr = total_clicks / total_impressions
cpc = total_spend / total_clicks

In [46]:
print("Total Cost:", round(total_spend, 2))
print("Total Conversions:", total_conversions)
print("Total Clicks:", total_clicks)
print("Total Impressions:", total_impressions)

print("\nConversion Rate:", round(conversion_rate, 4))
print("Cost per Conversion (CPA):", round(cpa, 2))
print("CTR:", round(ctr, 4))
print("CPC:", round(cpc, 2))

Total Cost: 130244.9
Total Conversions: 13363
Total Clicks: 688333
Total Impressions: 40473185

Conversion Rate: 0.0194
Cost per Conversion (CPA): 9.75
CTR: 0.017
CPC: 0.19

In [47]:
#Facebook insights

facebook_df = social_ads[social_ads["platform"] == "Facebook"]

In [48]:
fb_spend = facebook_df["cost"].sum()
fb_conversions = facebook_df["conversions"].sum()
fb_clicks = facebook_df["clicks"].sum()
fb_impressions = facebook_df["impressions"].sum()

In [49]:
fb_ctr = fb_clicks / fb_impressions
fb_cpc = fb_spend / fb_clicks
fb_conversion_rate = fb_conversions / fb_clicks
fb_cpa = fb_spend / fb_conversions

In [50]:
print("Total Cost:", round(fb_spend, 2))
print("Total Conversions:", fb_conversions)
print("Total Clicks:", fb_clicks)
print("Total Impressions:", fb_impressions)

print("\nCTR:", round(fb_ctr, 4))
print("CPC:", round(fb_cpc, 2))
print("Conversion Rate:", round(fb_conversion_rate, 4))
print("CPA:", round(fb_cpa, 2))

Total Cost: 18292.0
Total Conversions: 2395
Total Clicks: 88899
Total Impressions: 4541474

CTR: 0.0196
CPC: 0.21
Conversion Rate: 0.0269
CPA: 7.64

In [51]:
#Google insights

google_df = social_ads[social_ads["platform"] == "Google"]

In [52]:
ggl_spend = google_df["cost"].sum()
ggl_conversions = google_df["conversions"].sum()
ggl_clicks = google_df["clicks"].sum()
ggl_impressions = google_df["impressions"].sum()

In [53]:
ggl_ctr = ggl_clicks / ggl_impressions
ggl_cpc = ggl_spend / ggl_clicks
ggl_conversion_rate = ggl_conversions / ggl_clicks
ggl_cpa = ggl_spend / ggl_conversions

In [54]:
print("Total Cost:", round(ggl_spend, 2))
print("Total Conversions:", ggl_conversions)
print("Total Clicks:", ggl_clicks)
print("Total Impressions:", ggl_impressions)

print("\nCTR:", round(ggl_ctr, 4))
print("CPC:", round(ggl_cpc, 2))
print("Conversion Rate:", round(ggl_conversion_rate, 4))
print("CPA:", round(ggl_cpa, 2))

Total Cost: 37686.2
Total Conversions: 4218
Total Clicks: 137590
Total Impressions: 7223544

CTR: 0.019
CPC: 0.27
Conversion Rate: 0.0307
CPA: 8.93

In [55]:
#Tiktok insights

tiktok_df = social_ads[social_ads["platform"] == "TikTok"]

In [56]:
tt_spend = tiktok_df["cost"].sum()
tt_conversions = tiktok_df["conversions"].sum()
tt_clicks = tiktok_df["clicks"].sum()
tt_impressions = tiktok_df["impressions"].sum()

In [57]:
tt_ctr = tt_clicks / tt_impressions
tt_cpc = tt_spend / tt_clicks
tt_conversion_rate = tt_conversions / tt_clicks
tt_cpa = tt_spend / tt_conversions

In [58]:
print("Total Cost:", round(tt_spend, 2))
print("Total Conversions:", tt_conversions)
print("Total Clicks:", tt_clicks)
print("Total Impressions:", tt_impressions)

print("\nCTR:", round(tt_ctr, 4))
print("CPC:", round(tt_cpc, 2))
print("Conversion Rate:", round(tt_conversion_rate, 4))
print("CPA:", round(tt_cpa, 2))

Total Cost: 74266.7
Total Conversions: 6750
Total Clicks: 461844
Total Impressions: 28708167

CTR: 0.0161
CPC: 0.16
Conversion Rate: 0.0146
CPA: 11.0

In [59]:
social_ads.to_csv("social_ads.csv", index=False)